use_frameworks!

platform :ios, '8.0'

target 'CNLiveICloudPicker_Example' do
  pod 'CNLiveICloudPicker', :path => '../'

  target 'CNLiveICloudPicker_Tests' do
    inherit! :search_paths

    
  end
end
